### ISSUE TITLE
How does this is related to https://github.com/relan/exfat

### ISSUE THREAD

**Issue by tpgxyz** [namjaejeon/exfat-tools#40]
Hi,

https://github.com/relan/exfat released v1.3.0 in 2018. How that release is related to yours 1.0.1 ?
If yours 1.0.1 is successor than please bump the version to be higher tnat 1.3.0 so distributions and packages may handle this upgrade easier.

**Comment by namjaejeon** [comment]
Hi,
exfat-utils project is not related with fuse-exfat(relan/exfat).
Our exfat-utils project is the official userspace utilities for exfat filesystem which was recently merged into linux-5.7.
We will provide more reliable mkfs/fsck utilities for linux exfat filesystem to linux users.

**Comment by namjaejeon** [comment]
>If yours 1.0.1 is successor than please bump the version to be higher tnat 1.3.0 so distributions and packages may handle this upgrade easier.

Okay, We are implementing repair feature in fsck now. I may increment major version(1.0.1 -> 2.0.0) of exfat-utils on release included this feature.
Thanks for your opinion.

**Comment by vojtechtrefny** [comment]
Please also consider keeping backwards compatibility with the fuse exfat userspace utilities. I've already noticed first difference in command line options for `mkfs.exfat` -- you are using `-l` for label, the exfat fuse mkfs is using `-n`. `-l` definitely makes more sense but it would be really nice to also have `-n` for backwards compatibility.

**Comment by namjaejeon** [comment]
@vojtechtrefny Okay. We can make -n option fallthrough to -l option for backward compatibility with old utils. Thanks for your opinion.

**Comment by namjaejeon** [comment]
If needed, You can reopen it. For now, Closed.
